// This file is autogenerated, please do not modify directly!

#include "C:/cmangos/source/src/game/modules/mod_locale_chat/src/loader.h"
#include "C:/cmangos/source/src/game/modules/mod_sample/src/loader.h"


void AddScripts() {
    Addmod_sampleScripts();Addmod_localeScripts();
}
